const { Schema, model } = require('mongoose')

const iaaiCarSchema = new Schema({
    stock: String,
    sellingBranch: String,
    vin: String,
    status: String,
    loss: String,
    primaryDamage: String,
    secondDamage: String,
    titleSaleDoc: String,
    startCode: String,
    key: String,
    odometer: String,
    airbags: String,
    vinStatus: String,
    vehicle: String,
    bodyStyle: String,
    engine: String,
    transmission: String,
    driverLineType: String,
    fuelType: String,
    cylinders: String,
    restraintSystem: String,
    exteriorInterior: String,
    options: String,
    manufacturedIn: String,
    vehicleClass: String,
    model: String,
    series: String,
    buyNowPrice: String,
    startingBid: String,
    currentBid: String,
    vehicleLocation: String,
    auctionDateAndTime: String,
    laneRun: String,
    aisleStall: String,
    actualCashValue: String,
    seller: String,
    estimatedRepairCost: String,
    titleSaleDocBrand: String,
    sourcePhotos: String,
    link: String,
    timestamp: Number,
    downloadPath: String,
    archive: String,
    photos: [String]
})

module.exports = model('IaaiCar', iaaiCarSchema)
